### ISSUE TITLE
2do: threads

### ISSUE THREAD

**Issue by maxiller** [samdoran/rsync-time-machine#3]
On some crontab implementations (on embedded devices) every launch locks the main thread and crontab misses all its jobs if sync-time-machine takes long to run. This is especially actual for first backup in current month. 
I suggest to separate clean up phase to separate thread.

**Comment by samdoran** [comment]
I refactor the code a bit and put the cleanup section in a subshell. Please let me know if that solves your problem. Thanks for the feedback!
